# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/errbase/all/errbase.rbi
#
# errbase-0.1.1
module Errbase
  def self.report(e, info = nil); end
end
