# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/groupdate/all/groupdate.rbi
#
# groupdate-4.1.2
module Groupdate
  def dates; end
  def dates=(obj); end
  def day_start; end
  def day_start=(obj); end
  def self.dates; end
  def self.dates=(obj); end
  def self.day_start; end
  def self.day_start=(obj); end
  def self.process_result(relation, result, **options); end
  def self.time_zone; end
  def self.time_zone=(obj); end
  def self.week_start; end
  def self.week_start=(obj); end
  def time_zone; end
  def time_zone=(obj); end
  def week_start; end
  def week_start=(obj); end
end
class Groupdate::RelationBuilder
  def clean_group_clause_mysql(clause); end
  def clean_group_clause_postgresql(clause); end
  def column; end
  def day_start; end
  def generate; end
  def group_clause; end
  def initialize(relation, column:, period:, time_zone:, time_range:, week_start:, day_start:); end
  def period; end
  def resolve_column(relation, column); end
  def week_start; end
  def where_clause; end
end
class Groupdate::SeriesBuilder
  def check_consistent_time_zone_info(data, multiple_groups, group_index); end
  def day_start; end
  def entire_series?(series_default); end
  def generate(data, default_value:, series_default: nil, multiple_groups: nil, group_index: nil); end
  def generate_series(data, multiple_groups, group_index); end
  def handle_multiple(data, series, multiple_groups, group_index); end
  def initialize(period:, time_zone:, day_start:, week_start:, **options); end
  def key_format; end
  def now; end
  def options; end
  def period; end
  def round_time(time); end
  def time_range; end
  def time_zone; end
  def week_start; end
end
class Groupdate::Magic
  def day_start; end
  def group_index; end
  def group_index=(arg0); end
  def initialize(period:, **options); end
  def options; end
  def options=(arg0); end
  def period; end
  def period=(arg0); end
  def series_builder; end
  def time_range; end
  def time_zone; end
  def week_start; end
end
class Groupdate::Magic::Enumerable < Groupdate::Magic
  def group_by(enum, &_block); end
  def self.group_by(enum, period, options, &block); end
end
class Groupdate::Magic::Relation < Groupdate::Magic
  def cast_method; end
  def cast_result(result, multiple_groups); end
  def check_nils(result, multiple_groups, relation); end
  def initialize(**options); end
  def perform(relation, result, default_value:); end
  def self.generate_relation(relation, field:, **options); end
  def self.process_result(relation, result, **options); end
  def time_zone_support?(relation); end
end
module Enumerable
  def group_by_day(*args, &block); end
  def group_by_day_of_month(*args, &block); end
  def group_by_day_of_week(*args, &block); end
  def group_by_hour(*args, &block); end
  def group_by_hour_of_day(*args, &block); end
  def group_by_minute(*args, &block); end
  def group_by_minute_of_hour(*args, &block); end
  def group_by_month(*args, &block); end
  def group_by_month_of_year(*args, &block); end
  def group_by_period(*args, &block); end
  def group_by_quarter(*args, &block); end
  def group_by_second(*args, &block); end
  def group_by_week(*args, &block); end
  def group_by_year(*args, &block); end
end
module Groupdate::QueryMethods
  def group_by_day(field, time_zone = nil, range = nil, **options); end
  def group_by_day_of_month(field, time_zone = nil, range = nil, **options); end
  def group_by_day_of_week(field, time_zone = nil, range = nil, **options); end
  def group_by_hour(field, time_zone = nil, range = nil, **options); end
  def group_by_hour_of_day(field, time_zone = nil, range = nil, **options); end
  def group_by_minute(field, time_zone = nil, range = nil, **options); end
  def group_by_minute_of_hour(field, time_zone = nil, range = nil, **options); end
  def group_by_month(field, time_zone = nil, range = nil, **options); end
  def group_by_month_of_year(field, time_zone = nil, range = nil, **options); end
  def group_by_period(period, field, permit: nil, **options); end
  def group_by_quarter(field, time_zone = nil, range = nil, **options); end
  def group_by_second(field, time_zone = nil, range = nil, **options); end
  def group_by_week(field, time_zone = nil, range = nil, **options); end
  def group_by_year(field, time_zone = nil, range = nil, **options); end
end
module Groupdate::Relation
  def calculate(*args, &block); end
  extend ActiveSupport::Concern
end
class ActiveRecord::Base
  extend Groupdate::QueryMethods
end
class ActiveRecord::Relation
  def groupdate_values; end
  def groupdate_values=(arg0); end
  include Groupdate::Relation
end
class Groupdate::Error < RuntimeError
end
