# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/safely_block/all/safely_block.rbi
#
# safely_block-0.2.2
module Safely
  def self.env; end
  def self.env=(arg0); end
  def self.raise_envs; end
  def self.raise_envs=(arg0); end
  def self.report_exception(e, tag: nil, context: nil); end
  def self.report_exception_method; end
  def self.report_exception_method=(arg0); end
  def self.tag; end
  def self.tag=(arg0); end
  def self.throttle_counter; end
  def self.throttle_counter=(arg0); end
  def self.throttled?(e, options); end
  extend Safely::Methods
end
module Safely::Methods
  def safely(tag: nil, sample: nil, except: nil, only: nil, silence: nil, throttle: nil, default: nil, context: nil); end
  def yolo(tag: nil, sample: nil, except: nil, only: nil, silence: nil, throttle: nil, default: nil, context: nil); end
end
