# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/searchjoy/all/searchjoy.rbi
#
# searchjoy-0.4.2
module Searchjoy
  def conversion_name; end
  def conversion_name=(obj); end
  def query_name; end
  def query_name=(obj); end
  def query_url; end
  def query_url=(obj); end
  def self.attach_to_searchkick!; end
  def self.conversion_name; end
  def self.conversion_name=(obj); end
  def self.query_name; end
  def self.query_name=(obj); end
  def self.query_url; end
  def self.query_url=(obj); end
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.table_name_prefix; end
  def self.time_zone; end
  def self.time_zone=(time_zone); end
  def self.top_searches; end
  def self.top_searches=(obj); end
  def self.use_relative_model_naming?; end
  def time_zone; end
  def top_searches; end
  def top_searches=(obj); end
end
module Searchjoy::Track
end
module Searchjoy::Track::Query
  def execute; end
  def search; end
  def track; end
end
module Searchjoy::Track::MultiSearch
  def perform; end
end
class Searchjoy::Engine < Rails::Engine
end
