# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/wit/all/wit.rbi
#
# wit-6.0.0
class Wit
  def delete_entities(entity_id); end
  def delete_expressions(entity_id, value, expression); end
  def delete_values(entity_id, value); end
  def get_entities; end
  def get_entity(entity_id); end
  def initialize(opts = nil); end
  def interactive(handle_message = nil, context = nil); end
  def logger; end
  def message(msg, n = nil, verbose = nil); end
  def post_entities(payload); end
  def post_expressions(entity_id, value, payload); end
  def post_values(entity_id, payload); end
  def put_entities(entity_id, payload); end
  def req(logger, access_token, meth_class, path, params = nil, payload = nil); end
  def validate_payload(payload); end
end
class Wit::Error < StandardError
end
